image: node:13

stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: node:latest
  only:
    - master
  script:
    - npm install -g @angular/cli@12.2.0
    - npm install
    - ng build
  artifacts:
    paths:
      - dist/
    expire_in: 2 hours
  cache:
    paths:
      - node_modules/
